# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validator


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[restaurants.validator.validate_category]),
        ),
    ]
