# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurantlocation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='user',
            new_name='owner',
        ),
    ]
